ошибку исправлю
Assets\_Project\Scripts\SaveData.cs(65,16): error CS0246: The type or namespace name 'ES3SerializableDictionary<,>' could not be found (are you missing a using directive or an assembly reference?)